const oldWORDS = [
  { word: "spider", difficulty: "easy" },
  { word: "spider", difficulty: "medium" },
  { word: "spider", difficulty: "hard" },
];

const WORDS = [
  { word: "beach", difficulty: "easy" },
  { word: "chair", difficulty: "easy" },
  { word: "peach", difficulty: "easy" },
  { word: "lemon", difficulty: "easy" },
  { word: "grape", difficulty: "easy" },
  { word: "mango", difficulty: "easy" },
  { word: "tiger", difficulty: "medium" },
  { word: "maple", difficulty: "medium" },
  { word: "cloud", difficulty: "medium" },
  { word: "horse", difficulty: "medium" },
  { word: "raven", difficulty: "medium" },
  { word: "flame", difficulty: "medium" },
  { word: "crown", difficulty: "medium" },
  { word: "snake", difficulty: "medium" },
  { word: "music", difficulty: "medium" },
  { word: "ocean", difficulty: "medium" },
  { word: "panda", difficulty: "medium" },
  { word: "eagle", difficulty: "medium" },
  { word: "quest", difficulty: "medium" },
  { word: "swift", difficulty: "medium" },
  { word: "brush", difficulty: "medium" },
  { word: "fairy", difficulty: "medium" },
  { word: "ivory", difficulty: "medium" },
  { word: "orbit", difficulty: "medium" },
  { word: "amber", difficulty: "medium" },
  { word: "clown", difficulty: "medium" },
  { word: "whisk", difficulty: "medium" },
  { word: "tulip", difficulty: "medium" },
  { word: "pearl", difficulty: "medium" },
  { word: "diver", difficulty: "medium" },
  { word: "mirth", difficulty: "medium" },
  { word: "blaze", difficulty: "medium" },
  { word: "zebra", difficulty: "medium" },
  { word: "opera", difficulty: "medium" },
  { word: "gecko", difficulty: "medium" },
  { word: "viper", difficulty: "medium" },
  { word: "jumbo", difficulty: "medium" },
  { word: "fable", difficulty: "medium" },
  { word: "whale", difficulty: "medium" },
  { word: "quota", difficulty: "medium" },
  { word: "globe", difficulty: "hard" },
  { word: "frost", difficulty: "hard" },
  { word: "coral", difficulty: "hard" },
  { word: "polar", difficulty: "hard" },
  { word: "comet", difficulty: "hard" },
  { word: "pixel", difficulty: "hard" },
  { word: "prism", difficulty: "hard" },
  { word: "storm", difficulty: "hard" },
];

export default WORDS;
